# -*- coding: utf-8 -*-
"""Copy of Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T31D6a6kBwhdlX8GcX7m1kIk8_14CwjR
"""

"""
1. Student Attendance Analysis
A college maintains the daily attendance details of its students in the form of a list containing student IDs. Some students may have attended multiple sessions on the same day. The administration wants to identify the longest continuous sequence of sessions in which no student ID is repeated. Develop a solution that determines the maximum length of such a sequence."""
def longest_unique_sequence(arr):
    seen = set()
    left = 0
    max_length = 0

    for right in range(len(arr)):
        while arr[right] in seen:
            seen.remove(arr[left])
            left += 1

        seen.add(arr[right])
        max_length = max(max_length, right - left + 1)

    return max_length


arr = [1, 2, 3, 1, 4, 5]
print(longest_unique_sequence(arr))

"""
2. Online Shopping Price Analysis
An online shopping application stores the prices of products viewed by a customer during a browsing session. The customer wants to identify a continuous range of products that provides the maximum possible total discount value. Given the discount values, determine the maximum value that can be obtained from any continuous range.
"""
def max_discount(arr):
    current = arr[0]
    maximum = arr[0]

    for i in range(1, len(arr)):
        current = max(arr[i], current + arr[i])
        maximum = max(maximum, current)

    return maximum


arr = [-2, -1, 3, -2, 4]
print(max_discount(arr))

"""
3. Rainwater Collection System
A city installs buildings of different heights along a straight road. During rainfall, water gets collected between taller buildings. The engineering team needs to calculate the total amount of water that can remain trapped after heavy rainfall based on the heights of the buildings.
"""


def trap(height):
    left = 0
    right = len(height) - 1

    left_max = 0
    right_max = 0
    water = 0

    while left < right:

        if height[left] <= height[right]:

            if height[left] >= left_max:
                left_max = height[left]
            else:
                water += left_max - height[left]

            left += 1

        else:

            if height[right] >= right_max:
                right_max = height[right]
            else:
                water += right_max - height[right]

            right -= 1

    return water


arr = [0, 1, 0, 2, 1, 0]
print(trap(arr))

"""
4. Employee Performance Analysis
A company stores the monthly performance scores of an employee for several months. The scores may contain both positive and negative values depending on the employee's performance. Management wants to identify the continuous period during which the employee achieved the highest overall performance.
"""

def max_performance(arr):
    current = arr[0]
    maximum = arr[0]

    for i in range(1, len(arr)):
        current = max(arr[i], current + arr[i])
        maximum = max(maximum, current)

    return maximum


arr = [-2, -1, 3, -2, 4]
print(max_performance(arr))

"""5. Product Sales Analysis
A retail company stores the daily sales quantity of a product for several consecutive days. Due to seasonal changes, some days may have negative adjustments. The company wants to identify the period that produced the highest multiplication of sales-related values. Develop a solution to determine this maximum product.
"""

def max_product(arr):
    current_max = arr[0]
    current_min = arr[0]
    maximum = arr[0]

    for i in range(1, len(arr)):
        if arr[i] < 0:
            current_max, current_min = current_min, current_max

        current_max = max(arr[i], current_max * arr[i])
        current_min = min(arr[i], current_min * arr[i])

        maximum = max(maximum, current_max)

    return maximum


arr = [2, 3, -2, 4]
print(max_product(arr))

"""6. Customer Purchase History
An e-commerce application stores the product IDs purchased by a customer in chronological order. The same product may appear multiple times. The system needs to determine the longest sequence of consecutive purchases in which every product ID is unique.
"""

def lups(arr):
    seen = set()
    left = 0
    max_length = 0

    for right in range(len(arr)):
        while arr[right] in seen:
            seen.remove(arr[left])
            left += 1

        seen.add(arr[right])
        max_length = max(max_length, right - left + 1)

    return max_length

product_ids = [1, 2, 3, 1, 4, 5, 2, 6]
print(f"The longest sequence of unique purchases is: {lups(product_ids)}")

"""7. Bank Transaction Analysis
A bank stores transaction amounts for a customer's account. A continuous group of transactions may add up to a specific target amount. The auditing system needs to determine how many different continuous transaction groups produce exactly the specified amount.

"""

def count_subarrays(arr, target):
    prefix_sum = 0
    count = 0

    frequency = {0: 1}

    for num in arr:
        prefix_sum += num

        if prefix_sum - target in frequency:
            count += frequency[prefix_sum - target]

        frequency[prefix_sum] = frequency.get(prefix_sum, 0) + 1

    return count


arr = [1, 2, 3, -2, 2]
target = 3

print(count_subarrays(arr, target))

"""8. Employee Skill Grouping
A company receives a list of employee skill codes represented as strings. Employees having the same set of characters in their skill codes belong to the same skill category, even if the characters appear in a different order. The HR system needs to organize employees into appropriate skill groups.

"""

def group_skills(arr):
    groups = {}

    for skill in arr:
        key = ''.join(sorted(skill))

        if key not in groups:
            groups[key] = []

        groups[key].append(skill)

    return list(groups.values())


arr = ["eat", "tea", "tan", "ate", "nat", "bat"]

print(group_skills(arr))

"""9. Network Packet Analysis
A network monitoring system receives packet identifiers in chronological order. The system must determine the longest sequence of consecutive packets whose identifiers form a continuous numerical sequence, regardless of their original order in the incoming data.

"""
def longest_sequence(arr):
    numbers = set(arr)
    longest = 0

    for num in numbers:

        if num - 1 not in numbers:
            current = num
            length = 1

            while current + 1 in numbers:
                current += 1
                length += 1

            longest = max(longest, length)

    return longest


arr = [100, 4, 200, 1, 3, 2]

print(longest_sequence(arr))

"""
10. Hospital Appointment Scheduling
A hospital receives appointment requests represented by starting and ending times. Some appointments overlap with each other. The scheduling system needs to combine overlapping appointment periods so that the final schedule contains only non-overlapping time ranges.
"""

def merge_appointments(intervals):
    intervals.sort()

    merged = []

    for interval in intervals:
        start = interval[0]
        end = interval[1]

        if not merged or start > merged[-1][1]:
            merged.append([start, end])
        else:
            merged[-1][1] = max(merged[-1][1], end)

    return merged


appointments = [[1, 3], [2, 6], [8, 10], [9, 12]]

print(merge_appointments(appointments))